version: "3"
services:
  php:
    build:
        context: '.'
        dockerfile: ./docker/php/Dockerfile
    restart: always
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/html:cached
      - ./docker/php/custom.httpd.conf:/etc/httpd/conf.d/custom.httpd.conf
      - app-ignore-1:/var/www/html/test/template_c
    ports:
      - 80:80
    environment:
      FREVOCRM_INSTALLER_DB_HOST: "db"
      FREVOCRM_INSTALLER_DB_PORT: "3306"
      FREVOCRM_INSTALLER_DB_USER: "root"
      FREVOCRM_INSTALLER_DB_PASSWORD: "docker"
      FREVOCRM_INSTALLER_DB_NAME: "frevocrm"
      FREVOCRM_INSTALLER_DB_ROOT_USER: "root"
      FREVOCRM_INSTALLER_DB_ROOT_PASSWORD: "docker"
      # Xdebugの設定を有効にしたい場合は、mode=debug に変更してください
      XDEBUG_CONFIG: "mode=off client_host=host.docker.internal client_port=9003 start_with_request=yes"
      TZ: "Asia/Tokyo"

  headlesschrome:
    container_name: headlesschrome
    image: headlesschrome:latest
    build:
      context: "."
      dockerfile: ./docker/chrome-headless/Dockerfile
    volumes:
      - ./docker/chrome-headless:/var/www/html
      - ./test:/var/www/html/html2pdf/test
    ports:
     - "30080:80"
    privileged: true
    # command: /sbin/init
    command: >
      sh -c 'usermod -u `stat -c %u /html2pdf/` www-data
             groupmod -g `stat -c %u /html2pdf/` www-data
             chown -R www-data.www-data /var/www/html
             chown -R www-data.www-data /html2pdf
             exec /sbin/init'
    dns: 8.8.8.8
    # 自動起動の有効化
    restart: always

  db:
    build:
      context: "."
      dockerfile: ./docker/mysql/Dockerfile
    restart: always
    volumes:
      - db-store:/var/lib/mysql
      - db-log-store:/var/log/mysql
    environment:
      MYSQL_DATABASE: "frevocrm"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      MYSQL_ROOT_PASSWORD: "docker"
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
volumes:
  db-store:
  db-log-store:
  app-ignore-1: