import { format, subDays } from "date-fns";
import { FRDescribeFieldsType } from "../model/types/frBase";
import { base62ToInt, generateRandomString } from "./util";
import { FrBaseModule } from "../model/frBaseModule";
import { Page } from "@playwright/test";
import { FRDescribeFieldsTypeWithModuleName } from "../model/types/frTest";

// 以下のリストに含まれているものはテストしない
const dontTestFields = [
  // global ban
  "tags",
  "last_action_date",
  "isconvertedfromlead",
  "starred",
  "emailoptout",
  "modifiedby",
  "isconvertedfrompotential",

  // portal
  "from_portal",

  // inventory
  "taxclass",
  "tax4",
  "currency1",
  "txtAdjustment",
  "hdnSubTotal",
  "hdnGrandTotal",
  "hdnTaxType",
];

const dontTestFieldsFromModule = {
  Accounts: ["account_id"], // 理由：親アカウントへの自己参照。クイック作成ダイアログが表示されテストが停止してしまう
  Contacts: ["account_id"], // 理由：ダイアログが表示されるためテストが停止してしまう
  Invoice: [
    "contact_id", // 理由：ダイアログが表示されるためテストが停止してしまう
    "salesorder_id",
  ],
  ServiceContracts: ["used_units"], // 理由：なぜか数値が合わない（Workflow？）
  PriceBooks: ["currency_id"], // 理由：表示されない
  HelpDesk: ["cf_868"], // 理由：この環境固有のvarchar(10)カスタム項目。入力欄にmaxlengthが無く、生成値がDBで切り詰められて検証値と不一致になる
};

const isRichTextFields = {
  HelpDesk: ["description", "solution"],
  Faq: ["question", "faq_answer"],
};

/**
 * テストで利用しない項目を定義する
 * @returns boolean
 */
export const dontTestFieldsName = (
  field: FRDescribeFieldsTypeWithModuleName
) => {
  // 編集不可な項目はテストしない
  if (field.editable === false) {
    return true;
  }

  /************************
   * フィールド別対応
   ************************/
  if (dontTestFields.includes(field.name)) {
    return true;
  }

  /************************
   * モジュール別対応
   ************************/
  if (
    dontTestFieldsFromModule[field.moduleName] &&
    dontTestFieldsFromModule[field.moduleName].includes(field.name)
  ) {
    return true;
  }

  /************************
   * 任意の関連項目(reference)
   * 関連レコードの作成/選択モーダルは不安定でハングしやすく、
   * 任意項目は保存に不要なためテストしない。必須の関連項目のみ入力する。
   ************************/
  if (field.type.name === "reference" && field.mandatory !== true) {
    return true;
  }

  // 以下の項目タイプはテストしない
  const dontTestFieldTypes = [
    "multipicklist",
    // "reference", // できなくて良い
    "owner", // できなくて良い
    "datetime", // できなくて良い
    "autogenerated", // できなくて良い
    "image", // できなくて良い
  ];
  if (dontTestFieldTypes.includes(field.type.name)) {
    return true;
  }

  return false;
};

/**
 * FRDescribeFieldsType typeを受け取って、項目に適した値を返す
 */
export const getFieldValue = async (
  field: FRDescribeFieldsTypeWithModuleName,
  hash?: string
) => {
  if (dontTestFieldsName(field)) {
    return false;
  }

  // if(field.type.name === 'reference'){
  //   const moduleModel = await FrBaseModule.init(field.type.refersTo && field.type.refersTo[0] || '');
  //   if(!moduleModel){
  //     // return false;
  //   }
  //   const record = await moduleModel.getOneRecordFromModuleName(field.type.refersTo && field.type.refersTo[0] || '');
  //   if(!record){
  //     // return false;
  //   }
  //   // record.id は 22x1 のような形式なため、xで分割した後ろの数字だけを取得する
  //   const recordId = record.id.split('x')[1];
  // }

  switch (field.type.name) {
    case "string":
      return `${field.label}_${hash}`;
    case "text":
      return `${field.label}_${hash}`;
    case "url":
      return `http://example.com/${hash}`;
    case "email":
      return `${hash || "example"}@example.com`;
    case "integer":
    case "currency":
      // base62ToIntは最大約21億(10桁)になり、数値項目のバリデーション
      // (桁数/最大値)で保存が弾かれるモジュールがあるため、
      // 1〜99999(最大5桁)に収める。
      return ((Math.abs(base62ToInt(hash || "1")) % 99999) + 1).toString();
    case "double":
      return (Math.floor(Math.random() * 100) + 1).toString();
    case "date":
      const yesterday = subDays(new Date(), 1); // 前日の日付を取得
      return format(yesterday, "yyyy-MM-dd");
    case "phone":
      return `090-1234-5678`;
    case "picklist":
      return field.type.picklistValues?.[0].value || "";
    case "boolean":
      return "true";
    default:
      return `${field.label}_${hash}`;
  }
};

/**
 * フィールドに値を登録する
 */
export const fillField = async (
  page: Page,
  fieldObj: FRDescribeFieldsTypeWithModuleName,
  value: string,
  parentElement?: string
) => {
  const parentElementSelector = parentElement ? `${parentElement} ` : "";

  if (
    isRichTextFields[fieldObj.moduleName] &&
    isRichTextFields[fieldObj.moduleName].includes(fieldObj.name)
  ) {
    /**********************************************************************************************
     * リッチテキスト項目への値登録
     * エディタはJodit(contenteditableなdiv)。旧CKEditor(iframe)は廃止済み。
     * 値の実体は隠しtextareaに同期される。同じ項目セル内のJoditエディタ
     * (.jodit-wysiwyg)を特定して入力する。
     **********************************************************************************************/
    const richCell = page
      .locator(`#${fieldObj.moduleName}_editView_fieldName_${fieldObj.name}`)
      .locator('xpath=ancestor::*[contains(@class,"fieldValue")][1]');
    const editor = richCell.locator(".jodit-wysiwyg").first();
    await editor.click();
    await editor.fill(`${value}`);
    // Joditから隠しtextareaへ値を同期させる
    await editor.blur();
  } else if (fieldObj.type.name === "text") {
    /**********************************************************************************************
     * テキスト項目への値登録
     **********************************************************************************************/
    const selector = `${parentElementSelector} textarea[name="${fieldObj.name}"]`;
    const effective = await truncateToMaxlength(page, selector, value);
    await page.fill(selector, effective);
    return effective;
  } else if (fieldObj.type.name === "reference") {
    /**********************************************************************************************
     * 関連項目への値登録
     **********************************************************************************************/
    const createButton = await page.locator(
      `#${fieldObj.moduleName}_editView_fieldName_${fieldObj.name}_create`
    );

    // クリエイトボタンがない場合は、モーダルウインドウから選択する
    if (await createButton.isHidden()) {
      await page
        .locator(
          `#${fieldObj.moduleName}_editView_fieldName_${fieldObj.name}_select`
        )
        .click();
      await page.waitForLoadState("networkidle");
      await page.waitForLoadState("domcontentloaded");

      // .modal-body の .listview-table の .listViewEntriesの1つ目をクリック
      await page
        .locator(".modal-body .listview-table .listViewEntries")
        .first()
        .click();
    } else {
      await page
        .locator(
          `#${fieldObj.moduleName}_editView_fieldName_${fieldObj.name}_create`
        )
        .click();
      await page.waitForLoadState("networkidle");
      await page.waitForLoadState("domcontentloaded");
      // 値を登録する
      const relatedModule = await FrBaseModule.init(
        (fieldObj.type.refersTo && fieldObj.type.refersTo[0]) || ""
      );
      if (!relatedModule) {
        return false;
      }
      const relatedDescribe = await relatedModule.getDescribe();
      if (!relatedDescribe) {
        return false;
      }
      const hash = generateRandomString(8);
      const relatedFields = relatedDescribe.fields;
      const fieldsWithModuleName: FRDescribeFieldsTypeWithModuleName[] =
        relatedFields
          .map((info) => {
            return {
              moduleName:
                (fieldObj.type.refersTo && fieldObj.type.refersTo[0]) || "",
              ...info,
            };
          })
          .filter((info) => {
            return info.mandatory === true;
          });
      for (const [_key, fieldObj] of Object.entries(fieldsWithModuleName)) {
        if (dontTestFieldsName(fieldObj)) {
          continue;
        }

        const normalValue = (await getFieldValue(fieldObj, hash)) || "";
        await fillField(page, fieldObj, normalValue, ".modal-content");
      }
      await page.waitForTimeout(1000);

      await page.locator('button[name="saveButton"]').click();
    }
    await page.waitForLoadState("networkidle");
    await page.waitForTimeout(1000);
  } else if (fieldObj.type.name === "date") {
    /**********************************************************************************************
     * 日付項目への値登録
     **********************************************************************************************/
    const dateInput = page.locator(
      `${parentElementSelector} input[name="${fieldObj.name}"]`
    );
    await dateInput.fill(`${value}`);
    // datepickerのポップアップを閉じる。
    // - .fieldBlockHeader クリックは項目ブロックの開閉トグルを誘発し、複数
    //   日付モジュール(Products等)で保存ボタンが無効化される。
    // - Escapeはbootstrap-datepickerで入力値を取り消し、必須日付モジュール
    //   (Potentials等)で保存できなくなる。
    // blur()なら入力値を確定したままポップアップを閉じられる。
    await dateInput.blur();
  } else if (fieldObj.type.name === "picklist") {
    /**********************************************************************************************
     * 選択肢項目への値登録
     **********************************************************************************************/
    await page.selectOption(
      `${parentElementSelector} select[name=${fieldObj.name}]`,
      value
    );
  } else if (fieldObj.type.name === "boolean") {
    /**********************************************************************************************
     * チェックボックス項目への値登録
     **********************************************************************************************/
    await page.check(
      `${parentElementSelector} input[type="checkbox"][name="${fieldObj.name}"]`
    );
  } else {
    /**********************************************************************************************
     * それ以外すべての項目への値登録
     **********************************************************************************************/
    const selector = `${parentElementSelector} input[name="${fieldObj.name}"]`;
    const effective = await truncateToMaxlength(page, selector, value);
    await page.fill(selector, effective);
    return effective;
  }
};

/**
 * 入力欄のmaxlength属性に合わせて値を切り詰める。
 * Playwrightのfillはmaxlengthを無視して値を設定するため、明示的に切り詰めて
 * 保存時のDB切り詰めによる「入力値と保存値の不一致」を防ぐ。
 */
const truncateToMaxlength = async (
  page: Page,
  selector: string,
  value: string
): Promise<string> => {
  const maxlength = await page.getAttribute(selector, "maxlength").catch(() => null);
  if (maxlength) {
    const max = parseInt(maxlength, 10);
    if (!Number.isNaN(max) && max > 0) {
      return value.slice(0, max);
    }
  }
  return value;
};
