import { format, subDays } from "date-fns";
import { FRDescribeFieldsType } from "../model/types/frBase";
import { base62ToInt, generateRandomString } from "./util";
import { FrBaseModule } from "../model/frBaseModule";
import { Page } from "@playwright/test";
import { FRDescribeFieldsTypeWithModuleName } from "../model/types/frTest";

// 以下のリストに含まれているものはテストしない
const dontTestFields = [
  // global ban
  "tags",
  "last_action_date",
  "isconvertedfromlead",
  "starred",
  "emailoptout",
  "modifiedby",
  "isconvertedfrompotential",

  // portal
  "from_portal",

  // inventory
  "taxclass",
  "tax4",
  "currency1",
  "txtAdjustment",
  "hdnSubTotal",
  "hdnGrandTotal",
  "hdnTaxType",
];

const dontTestFieldsFromModule = {
  Accounts: ["account_id"], // 理由：親アカウントへの自己参照。クイック作成ダイアログが表示されテストが停止してしまう
  Contacts: ["account_id"], // 理由：ダイアログが表示されるためテストが停止してしまう
  Invoice: [
    "contact_id", // 理由：ダイアログが表示されるためテストが停止してしまう
    "salesorder_id",
  ],
  ServiceContracts: ["used_units"], // 理由：なぜか数値が合わない（Workflow？）
  PriceBooks: ["currency_id"], // 理由：表示されない
};

const isRichTextFields = {
  HelpDesk: ["description", "solution"],
  Faq: ["question", "faq_answer"],
};

/**
 * テストで利用しない項目を定義する
 * @returns boolean
 */
export const dontTestFieldsName = (
  field: FRDescribeFieldsTypeWithModuleName
) => {
  // 編集不可な項目はテストしない
  if (field.editable === false) {
    return true;
  }

  /************************
   * フィールド別対応
   ************************/
  if (dontTestFields.includes(field.name)) {
    return true;
  }

  /************************
   * モジュール別対応
   ************************/
  if (
    dontTestFieldsFromModule[field.moduleName] &&
    dontTestFieldsFromModule[field.moduleName].includes(field.name)
  ) {
    return true;
  }

  /************************
   * 任意の関連項目(reference)
   * 関連レコードの作成/選択モーダルは不安定でハングしやすく、
   * 任意項目は保存に不要なためテストしない。必須の関連項目のみ入力する。
   ************************/
  if (field.type.name === "reference" && field.mandatory !== true) {
    return true;
  }

  // 以下の項目タイプはテストしない
  const dontTestFieldTypes = [
    "multipicklist",
    // "reference", // できなくて良い
    "owner", // できなくて良い
    "datetime", // できなくて良い
    "autogenerated", // できなくて良い
    "image", // できなくて良い
  ];
  if (dontTestFieldTypes.includes(field.type.name)) {
    return true;
  }

  return false;
};

/**
 * FRDescribeFieldsType typeを受け取って、項目に適した値を返す
 */
export const getFieldValue = async (
  field: FRDescribeFieldsTypeWithModuleName,
  hash?: string
) => {
  if (dontTestFieldsName(field)) {
    return false;
  }

  // if(field.type.name === 'reference'){
  //   const moduleModel = await FrBaseModule.init(field.type.refersTo && field.type.refersTo[0] || '');
  //   if(!moduleModel){
  //     // return false;
  //   }
  //   const record = await moduleModel.getOneRecordFromModuleName(field.type.refersTo && field.type.refersTo[0] || '');
  //   if(!record){
  //     // return false;
  //   }
  //   // record.id は 22x1 のような形式なため、xで分割した後ろの数字だけを取得する
  //   const recordId = record.id.split('x')[1];
  // }

  switch (field.type.name) {
    case "string":
      return `${field.label}_${hash}`;
    case "text":
      return `${field.label}_${hash}`;
    case "url":
      return `http://example.com/${hash}`;
    case "email":
      return `${hash || "example"}@example.com`;
    case "integer":
    case "currency":
      // base62ToIntは最大約21億(10桁)になり、数値項目のバリデーション
      // (桁数/最大値)で保存が弾かれるモジュールがあるため、
      // 1〜99999(最大5桁)に収める。
      return ((Math.abs(base62ToInt(hash || "1")) % 99999) + 1).toString();
    case "double":
      return (Math.floor(Math.random() * 100) + 1).toString();
    case "date":
      const yesterday = subDays(new Date(), 1); // 前日の日付を取得
      return format(yesterday, "yyyy-MM-dd");
    case "phone":
      return `090-1234-5678`;
    case "picklist":
      return field.type.picklistValues?.[0].value || "";
    case "boolean":
      return "true";
    default:
      return `${field.label}_${hash}`;
  }
};

/**
 * フィールドに値を登録する
 */
export const fillField = async (
  page: Page,
  fieldObj: FRDescribeFieldsTypeWithModuleName,
  value: string,
  parentElement?: string
) => {
  const parentElementSelector = parentElement ? `${parentElement} ` : "";
  // 編集フォーム上の当該項目の一意ID。
  // name属性だけだと一覧検索フィルタ等の同名inputと衝突(strict mode違反)する
  // ことがあるため、編集フィールドはこのIDでスコープする。
  const editId = `#${fieldObj.moduleName}_editView_fieldName_${fieldObj.name}`;

  if (
    isRichTextFields[fieldObj.moduleName] &&
    isRichTextFields[fieldObj.moduleName].includes(fieldObj.name)
  ) {
    /**********************************************************************************************
     * リッチテキスト項目への値登録
     * エディタはJodit(contenteditableなdiv)。旧CKEditor(iframe)は廃止済み。
     * 値の実体は隠しtextareaに同期される。同じ項目セル内のJoditエディタ
     * (.jodit-wysiwyg)を特定して入力する。
     **********************************************************************************************/
    const richCell = page
      .locator(`#${fieldObj.moduleName}_editView_fieldName_${fieldObj.name}`)
      .locator('xpath=ancestor::*[contains(@class,"fieldValue")][1]');
    const editor = richCell.locator(".jodit-wysiwyg").first();
    await editor.click();
    await editor.fill(`${value}`);
    // Joditから隠しtextareaへ値を同期させる
    await editor.blur();
  } else if (fieldObj.type.name === "text") {
    /**********************************************************************************************
     * テキスト項目への値登録
     **********************************************************************************************/
    await page.fill(
      `${parentElementSelector} textarea[name="${fieldObj.name}"]`,
      `${value}`
    );
  } else if (fieldObj.type.name === "reference") {
    /**********************************************************************************************
     * 関連項目への値登録
     * 既存レコードを選択する方式に統一する。新規作成モーダルは参照先モジュール
     * ごとに構造が異なり不安定でハングしやすいため。参照先には事前にレコードが
     * 存在している必要がある(なければ呼び出し側でシードする)。
     **********************************************************************************************/
    const selectButton = page.locator(
      `#${fieldObj.moduleName}_editView_fieldName_${fieldObj.name}_select`
    );
    // 選択ボタンが無い関連項目(インベントリ明細のproductid等)は標準UIで扱えない
    // ため、ここでは何もしない(明細はモジュール側の専用処理で登録する)。
    if ((await selectButton.count()) === 0) {
      return;
    }
    await selectButton.click();
    await page.waitForLoadState("networkidle");

    // 参照先モジュールの一覧モーダルから先頭レコードを選択する。
    // モーダルの描画完了前にクリックすると選択が成立せずモーダルが開いたまま
    // 残り後続操作(保存ボタン)を覆うため、エントリの表示を待ってからクリックし、
    // モーダルが閉じる(選択完了)のを待つ。
    const entry = page
      .locator(".modal-body .listview-table .listViewEntries")
      .first();
    await entry.waitFor({ state: "visible", timeout: 15000 });
    await entry.click();
    await page
      .locator("#popupModal")
      .waitFor({ state: "hidden", timeout: 10000 })
      .catch(() => {});
    await page.waitForTimeout(300);
  } else if (fieldObj.type.name === "date") {
    /**********************************************************************************************
     * 日付項目への値登録
     **********************************************************************************************/
    const dateInput = page.locator(
      parentElement ? `${parentElementSelector} input[name="${fieldObj.name}"]` : editId
    );
    await dateInput.fill(`${value}`);
    // datepickerのポップアップを閉じる。
    // - .fieldBlockHeader クリックは項目ブロックの開閉トグルを誘発し、複数
    //   日付モジュール(Products等)で保存ボタンが無効化される。
    // - Escapeはbootstrap-datepickerで入力値を取り消し、必須日付モジュール
    //   (Potentials等)で保存できなくなる。
    // blur()なら入力値を確定したままポップアップを閉じられる。
    await dateInput.blur();
  } else if (fieldObj.type.name === "picklist") {
    /**********************************************************************************************
     * 選択肢項目への値登録
     **********************************************************************************************/
    await page.selectOption(
      `${parentElementSelector} select[name=${fieldObj.name}]`,
      // picklistのvalueが数値の場合があるため文字列化する
      String(value)
    );
  } else if (fieldObj.type.name === "boolean") {
    /**********************************************************************************************
     * チェックボックス項目への値登録
     * 生のcheckboxはカスタムのトグルUIで隠されており、クリックでは状態が変わらない
     * ことがある。送信される値はinput自体のchecked状態なので、JSで直接ONにして
     * changeイベントを発火させる。
     **********************************************************************************************/
    await page
      .locator(`${editId}[type="checkbox"], ${editId}`)
      .first()
      .evaluate((el) => {
        const cb = el as HTMLInputElement;
        if (!cb.checked) {
          cb.checked = true;
          cb.dispatchEvent(new Event("change", { bubbles: true }));
        }
      })
      .catch(() => {});
  } else {
    /**********************************************************************************************
     * それ以外すべての項目への値登録
     **********************************************************************************************/
    await page.fill(
      `${parentElementSelector} input[name="${fieldObj.name}"]`,
      `${value}`
    );
  }
};
